def brand_name():
    return [{"no": 0, "brand_name": "",
                      "brand_description": ""},
            {"no": 1, "brand_name": "oppo",
                      "brand_description": "Oppo"},
            {"no": 2, "brand_name": "realme",
                      "brand_description": "Realme"},
            {"no": 3, "brand_name": "vivo",
                      "brand_description": "Vivo"},
            {"no": 4, "brand_name": "xiaomi",
                      "brand_description": "Xiaomi / Poco"},
            {"no": 5, "brand_name": "samsung",
                      "brand_description": "Samsung"}]

def oppo():
    return [{"no": 0,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a33_cph2137",
                       "device_description": "Oppo A33",
                       "firehose": "prog_firehose_ddr_Oppo_A33_A53_A53s.elf",
                       "storage": "emmc"},
            {"no": 1,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a53_cph2127",
                       "device_description": "Oppo A53",
                       "firehose": "prog_firehose_ddr_Oppo_A33_A53_A53s.elf",
                       "storage": "emmc"},
            {"no": 2,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a53s_cph2139",
                       "device_description": "Oppo A53s",
                       "firehose": "prog_firehose_ddr_Oppo_A33_A53_A53s.elf",
                       "storage": "emmc"},
            {"no": 3,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a73_cph2099",
                       "device_description": "Oppo A73",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 4,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a74_cph2219",
                       "device_description": "Oppo A74",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 5,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a76_cph2375",
                       "device_description": "Oppo A76",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 6,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_a95_cph2375",
                       "device_description": "Oppo A95",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 7,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_f17_cph2095",
                       "device_description": "Oppo F17",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 8,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_f19_cph2219",
                       "device_description": "Oppo F19",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 9,  "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_f21pro_cph2219",
                       "device_description": "Oppo F21 Pro",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"},
            {"no": 10, "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_reno4_oldsec_cph2113",
                       "device_description": "Oppo Reno4 (Old security)",
                       "firehose": "prog_firehose_ddr_OppoReno4OldSec2019.mbn",
                       "storage": "ufs"},
            {"no": 11, "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_reno4_newsec_cph2113",
                       "device_description": "Oppo Reno4 (New security)",
                       "firehose": "prog_firehose_ddr_Oppo_Reno4NewSec2021CPH2113_Reno4ProCPH2109_Reno5CPH2159_Reno4G_Reno6CPH2235.elf",
                       "storage": "ufs"},
            {"no": 12, "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_reno4pro_cph2109",
                       "device_description": "Oppo Reno4 Pro",
                       "firehose": "prog_firehose_ddr_Oppo_Reno4NewSec2021CPH2113_Reno4ProCPH2109_Reno5CPH2159_Reno4G_Reno6CPH2235.elf",
                       "storage": "ufs"},
            {"no": 13, "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_reno5_cph2159",
                       "device_description": "Oppo Reno5",
                       "firehose": "prog_firehose_ddr_Oppo_Reno4NewSec2021CPH2113_Reno4ProCPH2109_Reno5CPH2159_Reno4G_Reno6CPH2235.elf",
                       "storage": "ufs"},
            {"no": 14, "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_reno6_cph2235",
                       "device_description": "Oppo Reno6",
                       "firehose": "prog_firehose_ddr_Oppo_Reno4NewSec2021CPH2113_Reno4ProCPH2109_Reno5CPH2159_Reno4G_Reno6CPH2235.elf",
                       "storage": "ufs"},
            {"no": 15, "brand_name": "oppo",
                       "brand_description": "Oppo",
                       "device_name": "oppo_reno7_cph2363",
                       "device_description": "Oppo Reno7",
                       "firehose": "prog_firehose_ddr_OppoReno7CPH2363_OppoA73CPH2099_OppoA74CPH2119_OppoA76CPH2375_OppoA95CPH2365_OppoF17CPH2095_OppoF19CPH2219_OppoF21PRO.elf",
                       "storage": "ufs"}]

def realme():
    return [{"no": 0, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realme6pro_rmx2061",
                      "device_description": "Realme 6 Pro",
                      "firehose": "prog_firehose_ddr_Realme6Pro_Realme7Pro_Realme8Pro.elf",
                      "storage": "ufs"},
            {"no": 1, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realme7i_rmx2103",
                      "device_description": "Realme 7i",
                      "firehose": "prog_firehose_ddr_Realme7iRMX2103_Realme9RMX3521.elf",
                      "storage": "ufs"},
            {"no": 2, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realme7pro_rmx2170",
                      "device_description": "Realme 7 Pro",
                      "firehose": "prog_firehose_ddr_Realme6Pro_Realme7Pro_Realme8Pro.elf",
                      "storage": "ufs"},
            {"no": 3, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realme8pro_rmx3091",
                      "device_description": "Realme 8 Pro",
                      "firehose": "prog_firehose_ddr_Realme6Pro_Realme7Pro_Realme8Pro.elf",
                      "storage": "ufs"},
            {"no": 4, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realme9_rmx3521",
                      "device_description": "Realme 9",
                      "firehose": "prog_firehose_ddr_Realme6Pro_Realme7Pro_Realme8Pro.elf",
                      "storage": "ufs"},
            {"no": 5, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realmec15_rmx2195",
                      "device_description": "Realme C15",
                      "firehose": "prog_firehose_ddr_RealmeC15RMX2195_RealmeC17_RMX2101.elf",
                      "storage": "emmc"},
            {"no": 6, "brand_name": "realme",
                      "brand_description": "Realme",
                      "device_name": "realmec17_rmx2101",
                      "device_description": "Realme C17",
                      "firehose": "prog_firehose_ddr_RealmeC15RMX2195_RealmeC17_RMX2101.elf",
                      "storage": "emmc"}]

def vivo():
    return [{"no": 0,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_iq00",
                       "device_description": "Vivo IQ00 UI",
                       "firehose": "prog_firehose_ddr_vivo_IQOOU1_Y20_Y50T_V20.elf",
                       "storage": "ufs"},
            {"no": 1,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y20_oldsec",
                       "device_description": "Vivo Y20 (Old security)",
                       "firehose": "prog_firehose_ddr_vivo_Y20_Y20i_Y20s.elf",
                       "storage": "emmc"},
            {"no": 2,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y20_newsec",
                       "device_description": "Vivo Y20 (New security)",
                       "firehose": "prog_firehose_ddr_vivo_IQOOU1_Y20_Y50T_V20.elf",
                       "storage": "ufs"},
            {"no": 3,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y50t",
                       "device_description": "Vivo Y50T",
                       "firehose": "prog_firehose_ddr_vivo_IQOOU1_Y20_Y50T_V20.elf",
                       "storage": "ufs"},
            {"no": 4,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y53",
                       "device_description": "Vivo Y53",
                       "firehose": "prog_firehose_8917_ddr_vivo_y53_y53l.mbn",
                       "storage": "emmc"},
            {"no": 5,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y55",
                       "device_description": "Vivo Y55/L",
                       "firehose": "prog_emmc_firehose_8937_y91_y93_y95_v11.mbn",
                       "storage": "emmc"},
            {"no": 6,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y65",
                       "device_description": "Vivo Y65",
                       "firehose": "prog_firehose_8917_ddr_vivo_y65.mbn",
                       "storage": "emmc"},
            {"no": 7,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y71",
                       "device_description": "Vivo Y71",
                       "firehose": "prog_firehose_8917_ddr_vivo_y71.mbn",
                       "storage": "emmc"},
            {"no": 8,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y91",
                       "device_description": "Vivo Y91/i",
                       "firehose": "prog_emmc_firehose_8937_y91_y93_y95_v11.mbn",
                       "storage": "emmc"},
            {"no": 9,  "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y93",
                       "device_description": "Vivo Y93",
                       "firehose": "prog_emmc_firehose_8937_y91_y93_y95_v11.mbn",
                       "storage": "emmc"},
            {"no": 10, "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_y95",
                       "device_description": "Vivo Y95",
                       "firehose": "prog_emmc_firehose_8937_y91_y93_y95_v11.mbn",
                       "storage": "emmc"},
            {"no": 11, "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_v9",
                       "device_description": "Vivo V9",
                       "firehose": "prog_emmc_firehose_8953_ddr_vivo_v9.mbn",
                       "storage": "emmc"},
            {"no": 12, "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_v9yth",
                       "device_description": "Vivo V9 Youth",
                       "firehose": "prog_emmc_firehose_8953_ddr_vivo_v9_youth.mbn",
                       "storage": "emmc"},
            {"no": 13, "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_v11pro",
                       "device_description": "Vivo V11 Pro",
                       "firehose": "prog_emmc_firehose_8937_y91_y93_y95_v11.mbn",
                       "storage": "emmc"},
            {"no": 14, "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_v20_newsec",
                       "device_description": "Vivo V20",
                       "firehose": "prog_firehose_ddr_vivo_IQOOU1_Y20_Y50T_V20.elf",
                       "storage": "ufs"},
            {"no": 15, "brand_name": "vivo",
                       "brand_description": "Vivo",
                       "device_name": "vivo_v21e",
                       "device_description": "Vivo V21E",
                       "firehose": "prog_firehose_ddr_vivo_V21e.elf",
                       "storage": "ufs"}]

def xiaomi_poco():
    return [{"no": 0,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mi8ee_ursa",
                       "device_description": "Xiaomi Mi 8 EE",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_mi8ee_ursa_sig_rb1.elf",
                       "storage": "ufs"},
            {"no": 1,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mi8se_sirius",
                       "device_description": "Xiaomi Mi 8 SE",
                       "firehose": "prog_emmc_firehose_Sdm670_ddr_xiaomi_mi8se_sirius_sig_rb1.mbn",
                       "storage": "ufs"},
            {"no": 2,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mi8ud_equuleus",
                       "device_description": "Xiaomi Mi 8 UD",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_mi8ud_equuleus_sig_rb1.elf",
                       "storage": "ufs"},
            {"no": 3,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mi9t_rapahel",
                       "device_description": "Xiaomi Mi 9T",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_Mi9T.elf",
                       "storage": "ufs"},
            {"no": 4,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mi10lite_toco",
                       "device_description": "Xiaomi Mi 10 Lite",
                       "firehose": "prog_ufs_firehose_MiNote10Lite.elf",
                       "storage": "ufs"},
            {"no": 5,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mi11tpro_vili",
                       "device_description": "Xiaomi 11T Pro",
                       "firehose": "prog_ufs_firehose_Mi11TProUFS.elf",
                       "storage": "ufs"},
            {"no": 6,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mia2_jasime",
                       "device_description": "Xiaomi Mi A2",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_mia2_jasmine_rb2.elf",
                       "storage": "emmc"},
            {"no": 7,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mia2lite_daisy",
                       "device_description": "Xiaomi Mi A2 Lite",
                       "firehose": "prog_emmc_firehose_8953_ddr_mia2lite_daisy_rb1.mbn",
                       "storage": "emmc"},
            {"no": 8,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mimax2_chiron",
                       "device_description": "Xiaomi Mi Max 2",
                       "firehose": "prog_ufs_firehose_8998_ddr_xiaomi_mimax2_chiron_rb1.elf",
                       "storage": "ufs"},
            {"no": 9,  "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mimax3_nitrogen",
                       "device_description": "Xiaomi Mi Max 3",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_xiaomi1_mimax3_nitrogen_rb4.elf",
                       "storage": "emmc"},
            {"no": 10, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mimix_lithium",
                       "device_description": "Xiaomi Mi Mix",
                       "firehose": "prog_ufs_firehose_8996_ddr_xiaomi_mimix_lithium_rb1.elf",
                       "storage": "ufs"},
            {"no": 11, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mimix2s_polaris",
                       "device_description": "Xiaomi Mi Mix 2S",
                       "firehose": "prog_ufs_firehose_Sdm845_ddr_xiaomi_sig_mimix2s_polaris_rb1.elf",
                       "storage": "ufs"},
            {"no": 12, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mimix3_perseus",
                       "device_description": "Xiaomi Mi Mix 3",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_sig_mimix3_perseus_rb2.elf",
                       "storage": "ufs"},
            {"no": 13, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "minote2_scorpio",
                       "device_description": "Xiaomi Mi Note 2",
                       "firehose": "prog_ufs_firehose_8996_ddr_xiaomi_minote2_scorpio_rb1.elf",
                       "storage": "ufs"},
            {"no": 14, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "minote3_jason",
                       "device_description": "Xiaomi Mi Note 3",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_xiaomi_minote3_jason_rb1.elf",
                       "storage": "emmc"},
            {"no": 15, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "mipad4_clover",
                       "device_description": "Xiaomi Mi Pad 4",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_xiaomi_mipad4_clover_s_rb4.elf",
                       "storage": "emmc"},
            {"no": 16, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "pocof1_beryllium",
                       "device_description": "Xiaomi Poco F1",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_pocof1_beryllium_sig_rb1.mbn",
                       "storage": "ufs"},
            {"no": 17, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "pocom2pro_gramin",
                       "device_description": "Xiaomi Poco M2 Pro",
                       "firehose": "prog_ufs_firehose_MiPocoM2Pro.elf",
                       "storage": "ufs"},
            {"no": 18, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "pocom3_citrus",
                       "device_description": "Xiaomi Poco M3",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_MiPocoM3.elf",
                       "storage": "ufs"},
            {"no": 19, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "redmi5a_riva",
                       "device_description": "Xiaomi Redmi 5A",
                       "firehose": "prog_emmc_firehose_8953_ddr_xiaomi_redmi5a.mbn",
                       "storage": "emmc"},
            {"no": 20, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "redmi6pro_sakura",
                       "device_description": "Xiaomi Redmi 6 Pro",
                       "firehose": "prog_emmc_firehose_8953_ddr_xiaomi_6pro_sakura_rb1.mbn",
                       "storage": "emmc"},
            {"no": 21, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "redmi7_onclite",
                       "device_description": "Xiaomi Redmi 7",
                       "firehose": "prog_emmc_firehose_8953_ddr_redmi7_onc_onclite.mbn",
                       "storage": "emmc"},
            {"no": 22, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "redmi9t_lime",
                       "device_description": "Xiaomi Redmi 9T",
                       "firehose": "prog_ufs_firehose_sdm845_ddr_Mi9Power.elf",
                       "storage": "ufs"},
            {"no": 23, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "redmik20pro_raphael",
                       "device_description": "Xiaomi Redmi K20 Pro",
                       "firehose": "prog_ufs_firehose_RedmiK20Pro.elf",
                       "storage": "ufs"},
            {"no": 24, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note5_whyred",
                       "device_description": "Xiaomi Redmi Note 5",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_note5_whyred_s_rb4.elf",
                       "storage": "emmc"},
            {"no": 25, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note5pro_whyred",
                       "device_description": "Xiaomi Redmi Note 5 Pro",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_xiaomi_note5pro_whyred_s_rb4.elf",
                       "storage": "emmc"},
            {"no": 26, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note5a_ugglite",
                       "device_description": "Xiaomi Redmi Note 5A",
                       "firehose": "prog_emmc_firehose_8917_ddr_note5a_ugglite.mbn",
                       "storage": "emmc"},
            {"no": 27, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note6pro_tulip",
                       "device_description": "Xiaomi Redmi Note 6 Pro",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_xiaomi_note6pro_tulip_s_rb4.elf",
                       "storage": "emmc"},
            {"no": 28, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note7_lavender",
                       "device_description": "Xiaomi Redmi Note 7",
                       "firehose": "prog_emmc_firehose_Sdm660_ddr_redminote7_lavender.mbn",
                       "storage": "emmc"},
            {"no": 29, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note8_ginkgo",
                       "device_description": "Xiaomi Redmi Note 8",
                       "firehose": "prog_ufs_firehose_RedmiNote8.elf",
                       "storage": "ufs"},
            {"no": 30, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note9s_curtana",
                       "device_description": "Xiaomi Redmi Note 9S",
                       "firehose": "prog_ufs_firehose_MiNote9s.elf",
                       "storage": "ufs"},
            {"no": 31, "brand_name": "xiaomi",
                       "brand_description": "Xiaomi / Poco",
                       "device_name": "note9pro_joyeuse",
                       "device_description": "Xiaomi Redmi Note 9 Pro",
                       "firehose": "prog_ufs_firehose_MiNote9Pro.elf",
                       "storage": "ufs"}]

def samsung():
    return [{"no": 0, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_a015f",
                      "device_description": "Samsung A01 [SM-A015F]",
                      "firehose": "prog_emmc_firehose_8937_A015F.mbn",
                      "storage": "emmc"},
            {"no": 1, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_a025f",
                      "device_description": "Samsung A02 [SM-A025F]",
                      "firehose": "prog_emmc_firehose_8937_A025F.mbn",
                      "storage": "emmc"},
            {"no": 2, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_a115a",
                      "device_description": "Samsung A11 [SM-A115A]",
                      "firehose": "prog_emmc_firehose_8953_A115A.mbn",
                      "storage": "emmc"},
            {"no": 3, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_a115f",
                      "device_description": "Samsung A11 [SM-A115F]",
                      "firehose": "prog_emmc_firehose_8953_A115F.mbn",
                      "storage": "emmc"},
            {"no": 4, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_a115u",
                      "device_description": "Samsung A11 [SM-A115U]",
                      "firehose": "prog_emmc_firehose_8953_A115U.mbn",
                      "storage": "emmc"},
            {"no": 5, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_a705f",
                      "device_description": "Samsung A70 [SM-A705F]",
                      "firehose": "prog_ufs_firehose_ddr_A705F.mbn",
                      "storage": "ufs"},
            {"no": 6, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_j415f",
                      "device_description": "Samsung J4 Plus [SM-J415F]",
                      "firehose": "prog_ufs_firehose_8917_J415F.mbn",
                      "storage": "ufs"},
            {"no": 7, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_j610f",
                      "device_description": "Samsung J6 Plus [SM-J610F]",
                      "firehose": "prog_ufs_firehose_8917_J610F.mbn",
                      "storage": "ufs"},
            {"no": 8, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_m025f",
                      "device_description": "Samsung M02s [SM-M025F]",
                      "firehose": "prog_emmc_firehose_8953_M025F.mbn",
                      "storage": "emmc"},
            {"no": 9, "brand_name": "samsung",
                      "brand_description": "Samsung",
                      "device_name": "sm_m115f",
                      "device_description": "Samsung M11 [SM-M115F]",
                      "firehose": "prog_emmc_firehose_8953_M115F.mbn",
                      "storage": "emmc"}]

def command_method():
    return [{"command": "userdata",
             "description": "Factory reset"},
            {"command": "misc",
             "description": "Safe format data"},
            {"command": "micloud",
             "description": "Reset MiCloud"},
            {"command": "frp",
             "description": "Reset FRP"},
            {"command": "efs",
             "description": "Reset EFS"},
            {"command": "unlock_bl",
             "description": "Unlock Bootloader"},
            {"command": "unlock_bl_1",
             "description": "Unlock Bootloader (Fastboot: Method 1)"},
            {"command": "unlock_bl_2",
             "description": "Unlock Bootloader (Fastboot: Method 2)"},
            {"command": "relock_bl",
             "description": "Lock Bootloader"},
            {"command": "relock_bl_1",
             "description": "Lock Bootloader (Fastboot: Method 1)"},
            {"command": "relock_bl_2",
             "description": "Lock Bootloader (Fastboot: Method 2)"},
            {"command": "adb_recovery",
             "description": "Reboot to Recovery (ADB mode)"},
            {"command": "fastboot_recovery",
             "description": "Reboot to Recovery (Fastboot)"},
            {"command": "adb_fastboot",
             "description": "Reboot to Fastboot (ADB mode)"},
            {"command": "fastboot_reboot",
             "description": "Reboot to Fastboot (Fastboot)"},
            {"command": "adb_edl",
             "description": "Reboot to EDL mode (ADB mode)"},
            {"command": "fastboot_edl_1",
             "description": "Reboot to EDL mode (Fastboot: Method 1)"},
            {"command": "fastboot_edl_2",
             "description": "Reboot to EDL mode (Fastboot: Method 2)"},
            {"command": "fastboot_frp",
             "description": "Reset FRP (Fastboot)"},
            {"command": "fastboot_demo_1",
             "description": "Reset Demo mode (Fastboot: Method 1)"},
            {"command": "fastboot_demo_2",
             "description": "Reset Demo mode (Fastboot: Method 2)"},
            {"command": "adb_frp",
             "description": "Reset FRP (ADB mode)"},
            {"command": "adb_erasefrp",
             "description": "Erase FRP (ADB mode)"},
            {"command": "adb_pushfrp",
             "description": "Push FRP (ADB mode)"},
            {"command": "oppo_demo",
             "description": "Reset Oppo Demo mode (ADB mode)"}]
